In [2]:
import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
a1 = np.array([5,5,5])
a1

array([5, 5, 5])

In [4]:
type(a1)

numpy.ndarray

In [7]:
b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
len(b)

3

In [10]:
b[0]

array([5, 5, 5])

In [11]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [14]:
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [15]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [16]:
c = np.empty(5)
c

array([1., 1., 1., 1., 1.])

In [19]:
d = np.arange(2,20)
d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
d = np.arange(2,20,2)
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
d = np.linspace(10,20,num=5)
d

array([10. , 12.5, 15. , 17.5, 20. ])

In [28]:
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [29]:
i = np.ones(3, dtype=np.float64)
i

array([1., 1., 1.])

import numpy as np
a = np.ones((3,5) ,dtype=np.float)
a

In [16]:
d = np.arange(24).reshape(3,2,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

## numpy practice session

In [17]:
#import numpy in jupyter notebook
import numpy as np

## Create array using numpy

In [19]:
fruits = np.array(['apple','banana','grapes'])
fruits

array(['apple', 'banana', 'grapes'], dtype='<U6')

In [21]:
type(fruits)

numpy.ndarray

In [22]:
len(fruits)

3

In [23]:
fruits[1]

'banana'

In [25]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [26]:
type(price)

numpy.ndarray

In [27]:
price.mean()

5.0

In [28]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [32]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [46]:
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [47]:
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [48]:
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

## Array Function

In [49]:
a = np.array([1,5,25,100,9,7,6])
a

array([  1,   5,  25, 100,   9,   7,   6])

In [52]:
a.sort()
a

array([  1,   5,   6,   7,   9,  25, 100])

In [53]:
b=np.array([10.2,5,6,2,91,45])
b

array([10.2,  5. ,  6. ,  2. , 91. , 45. ])

In [55]:
c = np.concatenate((a,b))
c

array([  1. ,   5. ,   6. ,   7. ,   9. ,  25. , 100. ,  10.2,   5. ,
         6. ,   2. ,  91. ,  45. ])

In [56]:
c.sort()
c

array([  1. ,   2. ,   5. ,   5. ,   6. ,   6. ,   7. ,   9. ,  10.2,
        25. ,  45. ,  91. , 100. ])

## 2D- Array

In [65]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [59]:
b = np.array([[4,5],[6,7]])
b

array([[4, 5],
       [6, 7]])

In [68]:
c = np.array([[4,5,0,0,0],[6,7,0,0,0]])
c

array([[4, 5, 0, 0, 0],
       [6, 7, 0, 0, 0]])

In [73]:
d = np.concatenate((a, c), axis=0)
d

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [4, 5, 0, 0, 0],
       [6, 7, 0, 0, 0]])

In [75]:
d = np.concatenate((a, c), axis=1)
d

array([[1, 2, 3, 4, 5, 4, 5, 0, 0, 0],
       [5, 4, 3, 2, 1, 6, 7, 0, 0, 0]])

In [77]:
a = np.array([[[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [79]:
# Find number of dimention
a.ndim

3

In [2]:
import numpy as np
a = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [4]:
a.ndim

3

In [5]:
#number of elments
a.size

30

In [6]:
a.shape

(3, 2, 5)

In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
#reshape
np.reshape(a,newshape=(1,6), order = 'c') 

array([[0, 1, 2, 3, 4, 5]])

In [14]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b = np.array([1,2,3,4,5,6,7,8,9])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b.shape

(9,)

In [20]:
c = b[np.newaxis,:]
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
c.shape

(1, 9)

In [16]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
d = b[:,np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b[5:8]

array([6, 7, 8])

In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [3]:
c = np.linspace(0, 10, num=5)
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [18]:
c = np.concatenate((x, y), axis=0)
c


array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [20]:
array_example.ndim

3

In [21]:
array_example.size


24

In [22]:
array_example.shape


(3, 2, 4)

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [27]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [28]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
(a[a < 5])


array([1, 2, 3, 4])

In [29]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)


[ 2  4  6  8 10 12]


In [31]:
c = a[(a > 2) & (a < 11)]
c 

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [34]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [41]:
b1 = a[0, :]
b1


array([1, 2, 3, 4])

In [42]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [43]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [47]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [48]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [49]:
data.max()


2.0

In [50]:
data.sum()

3.0

In [51]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()


4.8595784

In [56]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [57]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
data[0, 1]


2

In [59]:
data[0]


array([1, 2])

In [60]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [61]:
data.max(axis=0)


array([5, 6])

In [62]:
data.max(axis=1)


array([2, 5, 6])

In [ ]:
np.ones((4, 3, 2))


array( [[[1,1],[1,1],[1,1]],
        [[1,1],[1,1],[1,1]],
        [[1,1],[1,1],[1,1]],
        [[1,1],[1,1],[1,1]]]
     )


[[],[],[]],

In [63]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.03437731, 0.64919848, 0.89858009])

In [64]:
rng.random((3, 2)) 


array([[0.21090596, 0.38623301],
       [0.42142468, 0.46647659],
       [0.08052009, 0.14719265]])

In [67]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [70]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [72]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0,return_counts=True,return_index=True)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
indices

array([0, 1, 2], dtype=int64)

In [82]:
occurrence_count

array([2, 1, 1], dtype=int64)

In [ ]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [84]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [85]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [87]:
reversed_arr_rows = np.flip(arr_2d, axis=1)
print(reversed_arr_rows)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [89]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [90]:
a?